### ISSUE TITLE
Notice of Official Fork

### ISSUE THREAD

**Issue by derks** [3ofcoins/docker-chef-server#10]
Unfortunately, it seems that the code base and Docker image here are no longer being maintained. I have attempted to help contribute to keep the project up-to-date, but the pull-requests have been un-merged.  I have also attempted to contact "offline" as well via email, but have not received any responses.

I appreciate all of the work that has gone into this project/repo, however for our needs we really require keeping in line with upstream stable versions from Chef and so it has become necessary to fork our own repo and maintenance of Chef Server for Docker.

We welcome any and all feedback and contributions:

 * [Docker Hub](https://hub.docker.com/r/trueability/chef-server/)
 * [Github](https://github.com/trueability/docker-chef-server)

**Comment by mpasternacki** [comment]
Thank you for your contributions, and let me apologize for my unresponsiveness. I understand your decision to go forward with your own image, and have linked to your repository in the README.

I will keep maintaining this image (as much time permits and as I need it – this is not a supported product, it is provided as is without any promises). I prefer this approach with single Ruby–based init script. Support for chef-server plugins, which you seem to need, is out of scope for this project.

I have merged the relevant changes from your PRs, updates to current 12.18.14, and changed logic of the automatic upgrade (look at version of the `chef-server-core` package rather than hostname, and run `chef-server-ctl upgrade` as described in the chef docs).
